<?php

namespace ImiecarBundle\Repository;
use ImiecarBundle\Entity\Trajet;

/**
 * TrajetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrajetRepository extends \Doctrine\ORM\EntityRepository
{

    public function findSearch(Trajet $trajet) {
        return $this->createQueryBuilder('t')
            ->where('t.date = :dateA')
            ->setParameter('dateA', $trajet->getDate())
            ->andWhere('t.villeDepart = :ville1')
            ->setParameter('ville1', $trajet->getVilleDepart())
            ->andWhere('t.villeArrivee = :ville2')
            ->setParameter('ville2', $trajet->getVilleArrivee())
            ->andWhere('t.heureDepart = :heure1')
            ->setParameter('heure1',$trajet->getHeureDepart())
            ->andWhere('t.heureArrivee = :heure2')
            ->setParameter('heure2', $trajet->getHeureArrivee())
            //->orderBy('p.price', 'ASC')
            ->getQuery()
            ->execute();
    }
}
