<?php

namespace ImiecarBundle\Repository;

/**
 * TrajetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrajetRepository extends \Doctrine\ORM\EntityRepository
{

    public function findSearch() {
        return $this->createQueryBuilder('t')
            ->where('t.date = :dateA')
            ->setParameter('dateA', '2017-03-11')
            //->orderBy('p.price', 'ASC')
            ->getQuery()
            ->execute();
    }
}
