<?php

namespace ImiecarBundle\Repository;
use ImiecarBundle\Entity\Trajet;

/**
 * TrajetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrajetRepository extends \Doctrine\ORM\EntityRepository
{

    public function findSearch(Trajet $trajet) {
        return $this->createQueryBuilder('t')
            ->where('t.date = :dateA')
            ->setParameter('dateA', $trajet->getDate())
            ->andWhere('t.villeDepart = :ville1')
            ->setParameter('ville1', $trajet->getVilleDepart())
            ->orWhere('t.villeIntermediaire = :villeI')
            ->setParameter('villeI', $trajet->getVilleDepart())
            ->andWhere('t.heureDepart >= :heure1')
            ->setParameter('heure1',$trajet->getHeureDepart()->format("H:i:s"))
            ->orWhere('t.heureIntermediaire >= :heureI')
            ->setParameter('heureI', $trajet->getHeureDepart()->format("H:i:s"))
            ->andWhere('t.villeArrivee = :ville2')
            ->setParameter('ville2', $trajet->getVilleArrivee())
            ->andWhere('t.heureArrivee <= :heure2')
            ->setParameter('heure2', $trajet->getHeureArrivee()->format("H:i:s"))

            ->getQuery()
            ->execute();
    }

    public function findRequest(Trajet $trajet)
    {
        return $this
            ->createQueryBuilder('t')
            ->update($this->getEntityName(), 't')
            ->set('t.nbPlaces', $trajet->getNbPlaces() - 1)
            ->where('t.id = :id')->setParameter('id', $trajet->getId())
            ->getQuery()
            ->execute();
    }

}
