oc_user:
    resource: "@OCUserBundle/Controller/"
    type:     annotation
    prefix:   /

imiecar:
    resource: "@ImiecarBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    path: /login
    defaults:
        _controller: OCUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout