imiecar_campus:
    resource: "@ImiecarBundle/Controller/CampusController.php"
    type:     annotation

imiecar_campus:
    resource: "@ImiecarBundle/Controller/CampusController.php"
    type:     annotation

imiecar_campus:
    resource: "@ImiecarBundle/Controller/CampusController.php"
    type:     annotation

imiecar_campus:
    resource: "@ImiecarBundle/Controller/CampusController.php"
    type:     annotation

imiecar_ville:
    resource: "@ImiecarBundle/Controller/villeController.php"
    type:     annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

imiecar:
    resource: "@ImiecarBundle/Controller/"
    type:     annotation
    prefix:   /

#login:
#    path: /login
#    defaults:
#        _controller: UserBundle:Security:login

login_check:
    path: /login_check


#logout:
#    path: /logout
#
